apiVersion: apps/v1

kind: StatefulSet

metadata:
  name: {{ .Values.mysql.microservice }}-statefulset
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/Version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ .Values.mysql.microservice }}
    {{- range $key,$value := .Values.mysql.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/Version: {{ .Chart.Version }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/component: {{ .Values.mysql.microservice }}
      {{- range $key,$value := .Values.mysql.labels }}
      {{ $key }}: {{ $value }}
      {{- end }}
  serviceName: {{ .Values.mysql.microservice }}-service-headless
  replicas: {{ .Values.mysql.replicas }}
  updateStrategy:
{{ .Values.mysql.updateStrategy | toYaml | indent 4 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/Version: {{ .Chart.Version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/component: {{ .Values.mysql.microservice }}
        {{- range $key,$value := .Values.mysql.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Values.mysql.microservice }}
        image: "{{ .Values.mysql.container.image.repo }}:{{ .Values.mysql.container.image.version }}"
        imagePullPolicy: {{ .Values.mysql.container.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mysql.container.port }}
        env:
{{ .Values.mysql.container.env | toYaml | indent 10 }}
        volumeMounts:
{{ .Values.mysql.container.volumeMounts | toYaml | indent 10 }}
  volumeClaimTemplates:
{{ .Values.mysql.volumeClaimTemplates | toYaml | indent 4 }}