apiVersion: v1

kind: Service

metadata:
  name: {{ .Values.mysql.microservice }}-service-headless

spec:
  type: None
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/Version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ .Values.mysql.microservice }}
    {{- range $key,$value := .Values.mysql.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  ports:
  - name: mysql
    port: {{ .Values.mysql.service.port }}
    targetPort: {{ .Values.mysql.service.targetPort }}