apiVersion: batch/v1

kind: Job

metadata:
  name: {{ .Values.mysql.microservice }}-job
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/Version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ .Values.mysql.microservice }}
    {{- range $key,$value := .Values.mysql.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}

spec:
  template:
    spec:
      containers:
      - name: setup-credentials
        image: "{{ .Values.mysql.container.image.repo }}:{{ .Values.mysql.container.image.version }}"
        env:
{{ .Values.mysql.job.container.env | toYaml | indent 10 }}
        command: ["/bin/sh", "-c"]
        args:
        - |
            while ! nc -zv "mysql-service" "3306"; do
              echo "MySQL is not available yet"
              sleep 5
            done

            echo "Creating users..."

            mysql -h mysql-service -u root -p"$MYSQL_ROOT_PASSWORD" <<EOF
            CREATE USER IF NOT EXISTS 'ratings'@'%' IDENTIFIED BY '${MYSQL_RATINGS_PASSWORD}';
            GRANT ALL PRIVILEGES ON ratings.* TO 'ratings'@'%';
            CREATE USER IF NOT EXISTS 'shipping'@'%' IDENTIFIED BY '${MYSQL_SHIPPING_PASSWORD}';.
            GRANT ALL PRIVILEGES ON cities.* TO 'shipping'@'%';
        EOF
        restartPolicy: {{ .Values.mysql.job.container.restartPolicy }}